# Generated by Django 6.0.1 on 2026-02-07 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0001_initial'),
        ('info', '0003_alter_studentcreate_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('written_full_marks', models.IntegerField(default=80)),
                ('oral_full_marks', models.IntegerField(default=20)),
                ('written_pass_marks', models.IntegerField(default=26)),
                ('oral_pass_marks', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.studentcreate')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_card.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_marks', models.IntegerField(default=0)),
                ('oral_marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('marksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='id_card.marksheet')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_card.subject')),
            ],
            options={
                'unique_together': {('marksheet', 'subject')},
            },
        ),
    ]
