# Generated by Django 6.0.1 on 2026-02-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0003_teacherassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='oral_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='written_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
