# Generated by Django 6.0.1 on 2026-02-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card', '0004_alter_mark_oral_marks_alter_mark_written_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
