# Generated by Django 6.0.1 on 2026-02-01 16:53

import django.core.validators
import info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='Enter your full name')),
                ('father_name', models.CharField(max_length=50, verbose_name='Enter your father name')),
                ('mother_name', models.CharField(max_length=50, verbose_name='Enter your mother name')),
                ('contact_number', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'সঠিক মোবাইল নাম্বার দিন')], verbose_name='Enter your contact number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Enter your email id if have')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('village', models.CharField(max_length=50, verbose_name='Enter your village name')),
                ('post_office', models.CharField(max_length=50, verbose_name='Enter your post office name')),
                ('police_station', models.CharField(max_length=50, verbose_name='Enter your police station name')),
                ('district', models.CharField(max_length=50, verbose_name='Enter your district name')),
                ('state', models.CharField(max_length=50, verbose_name='Enter your state name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', '৬ সংখ্যার পিন কোড দিন')], verbose_name='Enter your pin code')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', validators=[info.models.validate_image_size], verbose_name='Upload your current image (max 50kb)')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='Enter teacher full name')),
                ('father_name', models.CharField(max_length=50, verbose_name='Enter father name')),
                ('mother_name', models.CharField(max_length=50, verbose_name='Enter mother name')),
                ('contact_number', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'সঠিক মোবাইল নাম্বার দিন')], verbose_name='Enter contact number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Enter email id if have')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('village', models.CharField(max_length=50, verbose_name='Enter village name')),
                ('post_office', models.CharField(max_length=50, verbose_name='Enter post office name')),
                ('police_station', models.CharField(max_length=50, verbose_name='Enter police station name')),
                ('district', models.CharField(max_length=50, verbose_name='Enter district name')),
                ('state', models.CharField(max_length=50, verbose_name='Enter state name')),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', '৬ সংখ্যার পিন কোড দিন')], verbose_name='Enter pin code')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', validators=[info.models.validate_image_size], verbose_name='Upload teacher image (max 50kb)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['-created_at'],
            },
        ),
    ]
