# Generated by Django 6.0.1 on 2026-02-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Class Name')),
            ],
        ),
        migrations.AddField(
            model_name='studentcreate',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='info.studentclass'),
        ),
        migrations.AddField(
            model_name='studentcreate',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='info.studentclass'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=150)),
                ('passing_year', models.PositiveIntegerField()),
                ('result', models.CharField(blank=True, max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='info.teachercreate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('student_class', 'name')},
        ),
    ]
