# Generated by Django 6.0.1 on 2026-02-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_section_studentclass_studentcreate_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcreate',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.studentclass'),
        ),
    ]
